import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:evangelical_gospel_partner/core/data/providers/firestore_providers.dart';
import 'package:evangelical_gospel_partner/features/tenant/presentation/providers/tenant_providers.dart';
import 'package:evangelical_gospel_partner/core/data/models/announcements_models.dart';
import 'package:evangelical_gospel_partner/core/data/providers/firestore_providers.dart' as auth_core;
import 'package:evangelical_gospel_partner/core/domain/entities/announcements.dart' as entity;

final eventActionsProvider = Provider((ref) {
  final repository = ref.watch(eventRepositoryProvider);
  final tenantId = ref.watch(currentTenantIdProvider);
  final user = ref.watch(auth_core.firebaseAuthProvider).currentUser;

  return EventActions(repository, tenantId, user?.uid);
});

class EventActions {
  final dynamic repository;
  final String? tenantId;
  final String? userId;

  EventActions(this.repository, this.tenantId, this.userId);

  Future<void> createEvent({
    required String title,
    required String description,
    required String location,
    required DateTime startAt,
    required DateTime endAt,
    required int maxApplicants,
  }) async {
    if (tenantId == null || userId == null) return;

    final event = EventModel(
      id: '', // Generated by Firestore
      tenantId: tenantId!,
      title: title,
      description: description,
      location: location,
      startAt: startAt,
      endAt: endAt,
      maxApplicants: maxApplicants,
      currentApplicants: 0,
      status: entity.EventStatus.open,
      createdBy: userId!,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    await repository.add(event);
  }
}
