// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt9XuE8L6ZQ3lK5Q1jdJwquy-OFEhCXYM',
    appId: '1:750751683685:web:932d5e046d0a18717fe28c',
    messagingSenderId: '750751683685',
    projectId: 'egp-platform',
    authDomain: 'egp-platform.firebaseapp.com',
    storageBucket: 'egp-platform.firebasestorage.app',
    measurementId: 'G-6R5K4K1D43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRnuFJkQ7OT8VkbIhl6vUcSnQjP87SVaw',
    appId: '1:750751683685:android:5891535178d5f9057fe28c',
    messagingSenderId: '750751683685',
    projectId: 'egp-platform',
    storageBucket: 'egp-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1YfeuLJho3IRiDWr9Xv-PxVowXj6LWc',
    appId: '1:750751683685:ios:c9dbb0f944b53c2f7fe28c',
    messagingSenderId: '750751683685',
    projectId: 'egp-platform',
    storageBucket: 'egp-platform.firebasestorage.app',
    iosBundleId: 'com.glory903.egpp.evangelicalGospelPartner',
  );
}
