name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Get Dependencies
        run: |
          export PATH="$PATH:$HOME/flutter/bin"
          flutter pub get

      - name: Build Web
        run: |
          export PATH="$PATH:$HOME/flutter/bin"
          flutter build web --release --base-href "/evangelical-gospel-partner-platform/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
