name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 메인 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Flutter
        uses: subosito/flutter-action@f2c7f07530663d911a3d9021469e715694292b3a # v2.18.0
        with:
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Web
        # 중요: --base-href 뒤의 경로는 깃허브 저장소 이름과 일치해야 합니다.
        run: flutter build web --release --base-href "/evangelical-gospel-partner-platform/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9ac990e66d2146f84931a78368817b12267676 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
